const { 
  PlacementDrive, CompanyProfile, StudentProfile, User, Notification, 
  TestResult, MockSession, sequelize 
} = require('../models');
const { Op } = require('sequelize');
const sendEmail = require('../utils/emailService');

// --- ANALYTICS ---
exports.getAnalytics = async (req, res) => {
  try {
    const stats = await Promise.all([
      PlacementDrive.count({ where: { status: 'Ongoing' } }),
      PlacementDrive.findAll({
        attributes: [[sequelize.fn('AVG', sequelize.col('package_lpa')), 'avgCTC']],
        raw: true
      }),
      StudentProfile.count(), // In production this would use a flag like is_placed: true
    ]);

    res.json({
      success: true,
      data: {
        activeDrives: stats[0],
        avgCTC: parseFloat(stats[1][0]?.avgCTC || 0).toFixed(2),
        totalTracked: stats[2]
      }
    });
  } catch (e) {
    res.status(500).json({ success: false, message: e.message });
  }
};

// --- COMPANY REGISTRATION LIFECYCLE ---
exports.getCompanyVerifications = async (req, res) => {
  try {
    const companies = await CompanyProfile.findAll({
      order: [['createdAt', 'DESC']]
    });
    res.json({ success: true, data: companies });
  } catch (e) {
    res.status(500).json({ success: false, message: e.message });
  }
};

exports.approveCompany = async (req, res) => {
  try {
    const { id } = req.params;
    const company = await CompanyProfile.findByPk(id);
    if (!company) return res.status(404).json({ success: false, message: 'Entity not found' });

    company.is_verified = true;
    await company.save();
    res.json({ success: true, message: 'Verification privileges granted.' });
  } catch (e) {
    res.status(500).json({ success: false, message: e.message });
  }
};

// --- PLACEMENT DRIVE LIFECYCLE ---
exports.launchDrive = async (req, res) => {
  try {
    const { companyId, job_role, description, eligibility_cgpa, eligibility_branch, package_lpa, drive_date } = req.body;

    const newDrive = await PlacementDrive.create({
      companyId,
      job_role,
      description,
      eligibility_cgpa,
      eligibility_branch,
      package_lpa,
      drive_date,
      status: 'Upcoming'
    });

    res.status(201).json({ success: true, data: newDrive });
  } catch (e) {
    res.status(400).json({ success: false, message: e.message });
  }
};

// --- STUDENT READINESS & SCORES AGGREGATION ---
exports.getReadinessTracker = async (req, res) => {
  try {
    // Multi-nested query grabbing student basics + their derived system activity
    const students = await StudentProfile.findAll({
      include: [
        { model: User, attributes: ['name', 'email'] },
        { model: TestResult, attributes: ['score'] },
        { model: MockSession, attributes: ['overall_score'] }
      ],
      order: [['cgpa', 'DESC']]
    });
    res.json({ success: true, data: students });
  } catch (e) {
    res.status(500).json({ success: false, message: e.message });
  }
};

// --- BROADCAST CENTER (EMAILS + SYSTEM ALERTS) ---
exports.broadcastMessage = async (req, res) => {
  try {
    const { title, content, targetBranch, sendMailToggle } = req.body;

    // 1. Find eligible students
    const condition = targetBranch && targetBranch !== 'All' ? { branch: targetBranch } : {};
    const profiles = await StudentProfile.findAll({ where: condition, include: [User] });

    if (profiles.length === 0) {
      return res.status(404).json({ success: false, message: 'No students match target branch' });
    }

    // 2. Parallel dispatch loops
    const promises = profiles.map(async (student) => {
      // Native In-App alert
      await Notification.create({
        userId: student.User.id,
        title: `[TPO BROADCAST] ${title}`,
        message: content,
        type: 'Info'
      });

      // External SMTP relay if requested
      if (sendMailToggle && student.User.email) {
        try {
          await sendEmail({
            email: student.User.email,
            subject: `CRITICAL UPDATE: ${title}`,
            message: content,
            html: `<div style="font-family: sans-serif; padding: 20px; border-left: 4px solid #1e3a8a;">
                     <h2 style="color: #1e3a8a; margin-top: 0;">TPO Office Broadcast</h2>
                     <p>${content}</p>
                     <hr />
                     <small style="color: #9ca3af;">Generated by College Placement Intelligence Suite.</small>
                   </div>`
          });
        } catch (mailErr) {
          console.error(`Mail bounce to ${student.User.email}:`, mailErr.message);
        }
      }
    });

    await Promise.all(promises);
    res.json({ success: true, message: `Dispatched to ${profiles.length} endpoints.` });
  } catch (e) {
    res.status(500).json({ success: false, message: e.message });
  }
};

// --- REPORT EXPORT ENGINE ---
exports.exportReport = async (req, res) => {
  try {
    const data = await StudentProfile.findAll({ include: [User] });
    
    // Manual CSV Header construction
    let csv = "Name,Email,Branch,CGPA,Location\n";
    data.forEach(p => {
      csv += `"${p.User.name}","${p.User.email}","${p.branch}","${p.cgpa}","${p.location || ''}"\n`;
    });

    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', 'attachment; filename=student_report.csv');
    res.status(200).send(csv);
  } catch (e) {
    res.status(500).send("Export failed");
  }
};
